---
version: 2
jobs:
  build-haskell:
    docker:
      - image: savannidgerinel/haskell-webapp:latest

    working_directory: ~/repo/haskell
    
    steps:
      - checkout

      - restore_cache:
          key: stack-{{ checksum "orizentic.cabal" }}

      - run:
          name: build
          command: |
            cd haskell
            stack build

      - run:
          name: run tests
          command: |
            cd haskell
            stack test

      - save_cache:
          paths:
            - ~/.stack
          key: stack-{{ checksum "orizentic.cabal" }}

  build-go:
    docker:
      - image: savannidgerinel/golang:latest

    working_directory: /go/src/github.com/luminescent-dreams/orizentic

    steps:
      - checkout

      - run:
          name: build
          command: |
            cd go
            dep ensure
            go build ./...

      - run:
          name: test
          command: |
            cd go
            go get -u github.com/onsi/ginkgo/ginkgo
            ginkgo orizentic/...

  build-rust:
    docker:
      - image: rust:latest

    working_directory: ~/repo/rust

    steps:
      - checkout

      - restore_cache:
          key: rust-{{ checksum "Cargo.lock" }}

      - run:
          name: test
          command: |
            cargo test

      - run:
          name: build
          command: |
            cargo build --release

      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"

workflows:
  version: 2

  build-haskell:
    jobs:
      - build-haskell

  build-go:
    jobs:
      - build-go

  build-rust:
    jobs:
      - build-rust

